"""empty message

Revision ID: 503a820628f2
Revises: None
Create Date: 2015-10-12 19:00:23.453000

"""

# revision identifiers, used by Alembic.
revision = '503a820628f2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesOrder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salesOrderRow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['salesOrder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salesOrderRow')
    op.drop_table('salesOrder')
    ### end Alembic commands ###
